# Generated by Django 3.2.13 on 2022-05-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(verbose_name='date join')),
                ('person_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('confirmation_email_sent', models.BooleanField(default=0)),
            ],
        ),
    ]
